package app
import("context";"errors";"strings";"sync";"testing";"time";"github.com/amxv/angelos/internal/compose";"github.com/amxv/angelos/internal/dispatch";"github.com/amxv/angelos/internal/mail")
type memoryStore struct{mu sync.Mutex;record dispatch.Record;claimed bool;completeFails bool}
func(s *memoryStore)Put(_ context.Context,p compose.Prepared)error{s.record=dispatch.Record{Message:p,Status:"prepared"};return nil}
func(s *memoryStore)Claim(_ context.Context,id,digest string,_ time.Time)(dispatch.Record,bool,error){s.mu.Lock();defer s.mu.Unlock();if id!=s.record.Message.ID||digest!=s.record.Message.Digest{return dispatch.Record{},false,errors.New("mismatch")};if s.claimed{return s.record,false,nil};s.claimed=true;s.record.Status="sending";return s.record,true,nil}
func(s *memoryStore)Complete(_ context.Context,_ string,status,detail string)error{s.mu.Lock();defer s.mu.Unlock();if s.completeFails{return errors.New("store offline")};s.record.Status=status;s.record.Detail=detail;return nil}
type fakeSender struct{mu sync.Mutex;calls,appends int;status string;appendError bool}
func(s *fakeSender)Send(context.Context,mail.Envelope,[]byte)(mail.SendResult,error){s.mu.Lock();defer s.mu.Unlock();s.calls++;return mail.SendResult{Status:s.status,Stage:"acknowledgement"},nil}
func(s *fakeSender)AppendSent(context.Context,[]byte)(mail.MutationResult,error){s.mu.Lock();defer s.mu.Unlock();s.appends++;if s.appendError{return mail.MutationResult{},errors.New("append failed")};return mail.MutationResult{Status:"appended"},nil}
func TestSendConsumesIDOnceConcurrent(t *testing.T){for _,status:=range []string{"accepted","rejected","unknown"}{t.Run(status,func(t *testing.T){p:=compose.Prepared{ID:strings.Repeat("a",32),Digest:strings.Repeat("b",64),Raw:[]byte("fixture"),Recipients:[]string{"to@example.com"}};p.ExpiresAt=time.Now().Add(time.Minute);p.Digest=compose.WireDigest(p.From,p.Recipients,p.Raw);store:=&memoryStore{};store.Put(context.Background(),p);sender:=&fakeSender{status:status,appendError:true};a:=&App{Store:store,Submitter:sender};var wg sync.WaitGroup;for i:=0;i<10;i++{wg.Add(1);go func(){defer wg.Done();if _,e:=a.send(context.Background(),sendInput{p.ID,p.Digest,true});e!=nil{t.Error(e)}}()};wg.Wait();if sender.calls!=1{t.Fatalf("SMTP called %d times",sender.calls)};if status=="accepted"&&sender.appends!=1{t.Fatal("missing separate Sent append")};if status!="accepted"&&sender.appends!=0{t.Fatal("unaccepted send appended")}})}}
func TestWrongDigestDoesNotSend(t *testing.T){store:=&memoryStore{record:dispatch.Record{Message:compose.Prepared{ID:"correct",Digest:"correct"}}};sender:=&fakeSender{};a:=&App{Store:store,Submitter:sender};if _,e:=a.send(context.Background(),sendInput{"correct","wrong",false});e==nil||sender.calls!=0{t.Fatal("mismatch transmitted")}}
func TestStatusFailureDoesNotRetry(t *testing.T){p:=compose.Prepared{ID:strings.Repeat("a",32),Digest:strings.Repeat("b",64)};p.ExpiresAt=time.Now().Add(time.Minute);p.Digest=compose.WireDigest(p.From,p.Recipients,p.Raw);store:=&memoryStore{completeFails:true};store.Put(context.Background(),p);sender:=&fakeSender{status:"accepted"};a:=&App{Store:store,Submitter:sender};for i:=0;i<2;i++{if _,e:=a.send(context.Background(),sendInput{p.ID,p.Digest,false});e!=nil{t.Fatal(e)}};if sender.calls!=1{t.Fatal("repeated accepted send")}}
func TestCorruptPreparedContentDoesNotSend(t *testing.T){p:=compose.Prepared{ID:strings.Repeat("a",32),Raw:[]byte("approved"),ExpiresAt:time.Now().Add(time.Minute)};p.Digest=compose.WireDigest(p.From,p.Recipients,p.Raw);p.Raw=[]byte("modified");store:=&memoryStore{};store.Put(context.Background(),p);sender:=&fakeSender{};a:=&App{Store:store,Submitter:sender};if _,e:=a.send(context.Background(),sendInput{p.ID,p.Digest,false});e==nil||sender.calls!=0{t.Fatal("changed stored bytes sent")}}
